POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhHIiwiaWQiOiI2ODlhN2QyNDY4NDlmY2Y5YzBmZTMxYTIiLCJpYXQiOjE3NTU0NTUxMzIsImV4cCI6MTc1NTQ1ODczMn0.MoPjgHZv27AM35H4WeVyAtVb8BARP6EJmMecoEzfiZU

{
    "title": "Philosophy Talk",
    "author": "Philosophy Talk",
    "url": "https://philosophytalk.org"
}