DELETE http://localhost:3003/api/blogs/68ab420712d7c1f8385f7f1b
Content-Type: application/json
# Before sending this request, update the Blog ID in the URL above and copy-paste a new token below by running login.rest first.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhHIiwiaWQiOiI2ODlhN2QyNDY4NDlmY2Y5YzBmZTMxYTIiLCJpYXQiOjE3NTYwNTQwMDYsImV4cCI6MTc1NjA1NzYwNn0.BSPyz6oyJFkEcdA5pjTWSUMFKebrtgHvflE1mxf__6Y